services:
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    environment:
      - TZ=${TZ}
      - BESZEL_URL=${BESZEL_URL}
      - BESZEL_TOKEN=${BESZEL_TOKEN}
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`app.koye.casa`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  homelab-network:
    name: homelab-network
    external: true
